apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
  namespace: mysql-ns
spec:
  type: NodePort
  selector:
    app: mariadb  # Asegúrate que este label coincida con tu Deployment/StatefulSet
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 32307  # Puedes elegir un puerto entre 30000-32767
