apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls  # Nombre del Secret donde se guardará el certificado
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - argocd.migbertweb.xyz