apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-certificate
  namespace: kube-system
spec:
  secretName: headlamp-tls  # Nombre del Secret donde se guardará el certificado
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "headlamp.migbertweb.xyz"