apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - nodeport.yaml
  - statefulset.yaml
generators:
  - secrets/ksops-secret-generator.yaml