apiVersion: v1
kind: Service
metadata:
  name: mariadb-service # Cambiado a 'mariadb' para consistencia
  namespace: mysql-ns
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb # Asegúrate de cambiar la label también
  clusterIP: None