apiVersion: ENC[AES256_GCM,data:k+0=,iv:Da4Cad7wwNKD6+Y66kvfNpVD3t0OnNpJVHdKw3SM6ic=,tag:55ja2BajWNjlYsGMVSz3jw==,type:str]
kind: ENC[AES256_GCM,data:l+Wp/D4U,iv:5s9W63dK/jgks7kNY2PurowDHGqqUmpBaizTubMD2bQ=,tag:smlXu4k+9CXqlByFMI0oiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:it4Mho/mniX4ew31vnSX,iv:cwasULX+yFm1YzarXqCvA01+3hTkkY28z61hSoTAKn0=,tag:qC1/2vMw47W6f25+sxKtmQ==,type:str]
    namespace: ENC[AES256_GCM,data:pzgy6i7l4XGa3w==,iv:g99i+Z6ylYWps5aFEHXCJQEidewLYbgtiO6yWt0Pwsw=,tag:r0ynXJkuWx74H97ksuxgEQ==,type:str]
type: ENC[AES256_GCM,data:/oORdiU1,iv:SE1VjGWeHgzrh91R4W8ok4NZx0v23QxS7mUQ5bMQ4fM=,tag:dErPZqv2WW5Kymktp2x5zQ==,type:str]
#ENC[AES256_GCM,data:O45M8ga3fpaLR6xmq6rapOXFbYSGeBXnNlAj0mJcIQKjekZQgwPgI8UDLxIGRA==,iv:EOAdOvx4u9XzzQN5KD12wQ+kNk1vh7hjm5/IsxD0jT4=,tag:eKmY4SS4EyVee3Hq8T5lzg==,type:comment]
stringData:
    APP_KEY: ENC[AES256_GCM,data:Oe34JnuzPPq+aGR0tCNO5xYnjcfUSS/dVspmFJKHFXE3OxPWBK08oxS4AqYiUPmarjiU,iv:sp+QcpI5KEHrpjtYc2tm9IQ0IfCl4L4YobkySjXrnRc=,tag:WmtqH2q7e93S+OkDgMGEcw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:7+Kch6NnKhtT,iv:OeEFe/wpNc3AyTMPG7PFxun5mCgd117EWLhaX0nx8b0=,tag:SrzBXI4aMTGpAxKqsBvwjw==,type:str]
    #ENC[AES256_GCM,data:eKZMXFxCn5Rz,iv:ucelc76SnqouS5ftlw28on40buS1YjWSjxx9aTh0lB0=,tag:ihsam51BOTN0b9AgaDll6Q==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:EdfILUbrfzx9,iv:46pVtf1DzmgMB+Vm01eLOrYiFsynNkFZvsipSND59OY=,tag:L4mikc/5TX2RgauVORYobQ==,type:str]
sops:
    age:
        - recipient: age12t53xgmu88ye80jtnne6gcfgeytyvvsk6nyetep3xcdw0zthj5msr3dz2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOU95V1ZxbzJySGs2dDhp
            TlkzZWlYU0tIMVZTaHdNV0cvMzljc0tnbEVzCjFBWTdleUtON2kyYTVCdldEaXlW
            UWlPdVhrQ2lnSXY4eFkwVGVLK2VicHMKLS0tIHpKaHVCTWhRM25tUWxwL0RkYzlI
            L1Z1cU9VSnNjTS91RnNJSkd4RmxuTW8KPr7iy9NHQapSSRizOG7oCWq02NOQTvfV
            g5aHwuC9XOJuSij3VnvoY59uPLLlLvjl6FvwsCkHgd8sPXjxyrSBXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T20:42:09Z"
    mac: ENC[AES256_GCM,data:L0DyACQCOgv91jG6qGOFjETHbUEyb9PioVKFnP8gkEeWOpDQi0R+P2iGYPB6FZerr1pQWqJQQsuvwJJG+DVn9wp/U7k1UCDztHnzrcYza1/Q7havPzlzu31Nek4OPR8+vxE+IQ6QuGoPXWbnqMIdXsk+PLtKfyPgxktR89cF0m4=,iv:fQSL9XF14YuwY9DIsrgeVFGBSFV2EsMu7UYyFpjfVvY=,tag:wPJX/DbpI/p6XcUVTLnVPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
