apiVersion: ENC[AES256_GCM,data:gpc=,iv:ngl48jRNE/lD2/JdzQbSgUu2bC1pOFUBCS3PVaXx2i0=,tag:9aetPectDX3VsD1pdyEyRg==,type:str]
kind: ENC[AES256_GCM,data:7UbsPZJb,iv:InK+sCQL3kAe2+AEoOVjOVMWB4n4XTYjTTmQVkWMiWs=,tag:EuOupTr+YfqMxPNyjk7wYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F+edNk4f4a4UlKaOrvLE,iv:jKHV1u3hDNSYOsAbn2HOFLG4Czro5i33O5bUjo0PlpU=,tag:d1fuhqErMCyrHn7FXcymgg==,type:str]
    namespace: ENC[AES256_GCM,data:d9WPsEoEeamg6A==,iv:grQN+66rh0yUPo1izP1nqEMwJB+VCmQNHY4r6mkswxI=,tag:ElmHAod0CZsDcbNgOUtgeA==,type:str]
type: ENC[AES256_GCM,data:d0D9BF/3,iv:CxmgrUaiuh/PytYCrNQ6dPQ+1kmfp8YIdAAToELvC8I=,tag:qTGp7lpK/3RyQ9XimFbf3w==,type:str]
#ENC[AES256_GCM,data:/XeBdn+mjgvCrsomqkOP4iLi9PyusCW4lUH3c1w95j5BbF8dNINKVsOUJ5pb3A==,iv:r6Gwx4pyKQCEg8TFuZiNQDwmTwQBWJGBXwSDxr4toK8=,tag:wLvnXwD7mZBEaNsMYxoqwA==,type:comment]
stringData:
    APP_KEY: ENC[AES256_GCM,data:Xh3su8Qwxd8Hmj/X5uSR9k3+63j/BCs/EHQatXGsY2JX7AJyrDCsmyp+jXLfnFIrCTIw,iv:65V6kk4K4qqn8/DMCkugiKmzjavxyqaOVRBvpe4q+Ws=,tag:lYat0CXZ00Hat021hz/f2w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:d4OPxopVh+UW,iv:S/vz0zxclciFU33IqV6y3tCeUqAS72+qaH+tYKfSc6M=,tag:Rl40x8Ld9hZ3Ba56raXReA==,type:str]
    #ENC[AES256_GCM,data:WR9Sj5MUxIYP,iv:LsZWai9303mDgTEWEKDuBwUFW4QLHaxMoQ+PExzjRSw=,tag:mchHHyNJ3PpPYAprqIJpgQ==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:QNONnxGAo0wV,iv:fLPgbKOULi+phntrPkr42lUoOY0wtnGixwueEj1E4GY=,tag:xS+Iyr8aGfazvPYZadvWTQ==,type:str]
sops:
    age:
        - recipient: age12t53xgmu88ye80jtnne6gcfgeytyvvsk6nyetep3xcdw0zthj5msr3dz2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMDM1QUxsb0YzTGx2ZmlO
            NHljRU14cmcwbEtDMWpUM2tlYnJuVmoyL1dBCmZOeXNEOU5qV0dyOXhYbjY0anJy
            Zm5tYlgxK2hvMzNpSlpERms2VlRuZkkKLS0tIFJQaUxFeUZCMDdDeXFuVFAzSnVa
            eXN5d2VncGp6d05MNnJBT3NiaTZwU1kKznxAciZU8+rqhNubDYQ/FB2FVh/6KXmS
            1+VJUS81hYMYYDznO7q6PgF2FTeYqOOV73c7ZAaBIteGQOiAVYzuWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T01:24:17Z"
    mac: ENC[AES256_GCM,data:aAvhti8qjF6Ire3ku2PpZMTI3xRWUy3eAvWhRILZVb/tradsXvF03aVlHvbSR6gaD/eldCMXvzbWn2RZ3SHTTMcpKvgJhdKwM7ACCU4d3nA7zmMwWcsU2SlZLRSqXdSr3SvGQgv3ldFdw/al9FeUoNhh7lWd+6AIHaa3UfU2lMQ=,iv:5AUVL9vzfiU8ZXQA8/5vFzJkPvgEQ7cFNQ1PAwTWhl4=,tag:zbk6H9o+ZPL09Wk/9sjLnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
