apiVersion: ENC[AES256_GCM,data:fzI=,iv:ht7dF/UjAWArfgsIelIN110yh04I53J8JnhR0+6zM7w=,tag:nZ8LKHc4Nx08oaWFcRgJaA==,type:str]
kind: ENC[AES256_GCM,data:ItZTharq,iv:kpdMqjCj+p31dcTKIO6I1BgaGjSPXw44oGrN32qNfu4=,tag:oE+g0mQfNvb10XMiJiL/eg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yzraWhmyM574q/o0,iv:FsvUiQxMr3s+1Tg1CfFqf2e02/HDOinZeZ8OwZbAV84=,tag:SHNj17RSTAOZ1tCk+5ZY7w==,type:str]
type: ENC[AES256_GCM,data:oOaZ/hll,iv:hL8YCt7Ipm4JaFfPCHxivBk2k37g4Y3/4p3XRGJQnX4=,tag:t3B6I/8tCnKRlGzaYhgHwQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:4HwQXrhgF49K4e59D47J/iImkYX6Q9JGQ3WvyQkf87OmMdODd5JnNudOAypRKX80AkXFG3g=,iv:plJJnsH4rGoxw6SjhIfV2B0ydFsjaK3up649rbtnW0A=,tag:F0/1VoGDzxnTUE64OqWORA==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:pqbcbJ4XMhSh,iv:qeGsAYTC/qN3I6yiaKtIGVguo/jL7iQ3MJPiy5/vm6E=,tag:gAFaMWQJ5Q2E8fu6Mo1qrg==,type:str]
sops:
    age:
        - recipient: age12t53xgmu88ye80jtnne6gcfgeytyvvsk6nyetep3xcdw0zthj5msr3dz2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS2JHcFRQZk14RUxuMnkv
            R3FlanY0dTJ2aEQ4L1MxbVB5am0rVW9LUXdrCjlHRDVadXh4WHlwaFZEVFNxVE5B
            bitSNlg0QktDR1ozaVRldnJHRjFSNTgKLS0tIHlINlpUcldGeStTQ2xpVkxSOGVq
            UEJSWktLNk0vYzhWMXZCeFI5aXFhcW8KX6JGLilqHxW4V5ukPMtdWHyeA96l2LWM
            rwVts8GYiA4ePpa4U+ZnPW5mV+zCmqaoohvlPQjO5gDGCPPfovTNcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T01:24:26Z"
    mac: ENC[AES256_GCM,data:KbPlkw8qrtlx98rb4nVz0/AQ/WHqCg/yz3BD/McbKPWppNpPHbVz5LpBb+rgfvUXhXJ1RsuiIvCeHvi50fazcpyeXDq6XEQXg4IMfIC+lHn6Abd/9LteHlDrlBSIms0hDH07VEip9+RTMBu1uw7Ar+3LSllsYjsNhBqmjQS3/Iw=,iv:WeHfKabo1xiwsHpmaRazAJchrqIoN4F3+biCcje3Oqg=,tag:qV4fG1sNorFTWrba5RWwcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
