apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring  # Cambia esto si Grafana está en otro namespace
spec:
  secretName: grafana-tls  # Nombre del Secret donde se guardará el certificado
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - metrics.migbertweb.xyz