apiVersion: ENC[AES256_GCM,data:XKM=,iv:aJf5E3H2PDraYW3IpeUw+gd2xjIV4NWSWT8v/nQcyZg=,tag:I8jA7gAgMI4nLNE5RkE5TA==,type:str]
kind: ENC[AES256_GCM,data:cQX+rKpe,iv:R1/WB1f67H5K+bupXY0CMvQ9pcMBbd0xr5Ut2cKsvng=,tag:3cUsyIQT15Gy+syGPFWC2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ue7v3bH/DKwtPe7heG1J,iv:lwLGyiv/CCmEZX8HR+Oc+qMLcw0b8K4a2Z/gJdwWQYM=,tag:u/0qqmtNes5IUPLClqYy/Q==,type:str]
    namespace: ENC[AES256_GCM,data:KWt3e9UcBg==,iv:tB0FA74kzhsWsUO8FbqPK3Z6jn/2/zH5e72L3DOK9xc=,tag:Dxf92yoDEW5ppQdd0xLdIw==,type:str]
type: ENC[AES256_GCM,data:Pq62ikIH,iv:0IIg9FzD5dV9bqiZt9bnpHaQlSF290noPPAiEO9D6XE=,tag:rOhwwzkBfkgnHYKGt2p4AQ==,type:str]
stringData:
    USUARIO: ENC[AES256_GCM,data:BJdEPG1p,iv:rQV+gb+pKec9gXtaPOfeHjQbq6M9hKoersdsTybgGqQ=,tag:NkdJa7GzWjxnPRoI2zpTzA==,type:str]
    PASSWORD: ENC[AES256_GCM,data:wWaZx8Y8SDnqW952q5YF,iv:kpm6Ga1aw2vhLsSIFeUGVyNqmRM5xgV/hzkCgtij5QQ=,tag:a0ZQgScaKMcrKf5ixEhwxw==,type:str]
sops:
    age:
        - recipient: age12t53xgmu88ye80jtnne6gcfgeytyvvsk6nyetep3xcdw0zthj5msr3dz2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYzJuZlRVVjZEQUhtbDJX
            UmZxNDRCN2ZnRWsxVWhRTkVvallwbUVaVW5zCnR5dUVXKzNyV210QVZpbW9uTmdk
            MzF3ejZnT2oxTlRSeVdiQnNrRTU0RzAKLS0tIDE1czMvbUxZTDJPR09vY0FOeGFN
            Zzl3MFZPVXRXVEppbDNqRHdYK1BQTU0KNqHQT0zd1zPmIAFRegbpuolj9xol7I5t
            OTOFBCrTJ6IJaK++dwzdQhdcGCkjq5cMYxmxtERk0+KCGnc9MwXJ3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T23:22:13Z"
    mac: ENC[AES256_GCM,data:/WCAWrluvJiEO/CXYjzWikB6obkSXt1SUXq/zZMhkdS8MhHbn8mnDy6X21wp7HM2LnHtISA6qzFRmQoZKbwScDfMLaFSwCX4X0tFqda4ehsQ/64zxhN9K/xEle4qUNsjLny/1mFknGHTpo839F1mtkMwRqRl8suMXZgId7TO9Gk=,iv:mjNcZaKm8gaK6c/RZLII7qHBAnekmIm4jfbY+LQeCOo=,tag:l3ZvuO4miNY2T+riqi49nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
