# --- Prometheus Config ---
prometheus:
  prometheusSpec:
    maximumStartupDurationSeconds: 300  # Recommended: 300s (5 mins)
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    retention: 24h # Menos almacenamiento
    retentionSize: "500MB"  # Límite de espacio en disco
    replicaCount: 1 # Solo 1 réplica

# --- Alertmanager (deshabilitado) ---
alertmanager:
  enabled: false

# --- Pushgateway (deshabilitado) ---
pushgateway:
  enabled: false

# --- Node Exporter (HABILITADO para métricas de nodos) ---
nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# --- kube-state-metrics (HABILITADO para métricas del cluster) ---
kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# --- Grafana (HABILITADO con dashboards básicos) ---
grafana:
  enabled: true
  admin:
  ## Name of the secret. Can be templated.
    existingSecret: grafana-auth
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

ingress:
  enabled: false  # Deshabilitamos el Ingress tradicional de Nginx

# Configuración para Traefik IngressRoute
# ingressRoute:
#   enabled: true
#   entryPoints: 
#     - websecure
#   tls:
#     secretName: grafana-tls  # Nombre del Secret donde cert-manager guarda el certificado
#   routes:
#     - match: Host(`metrics.migbertweb.xyz`)
#       kind: Rule
#       services:
#         - name: grafana
#           port: 80

sidecar:
  dashboards:
    enabled: true

plugins:
  - grafana-kubernetes-app