apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-redis.yaml
  - redis-deployment.yaml
  - redis-service.yaml
generators:
  - secrets/ksops-generator.yaml