apiVersion: ENC[AES256_GCM,data:TT4=,iv:cMjvb5xUCa2MGjZ/1eh/0rH4N5Mfe2aIDfPLDE5WJyM=,tag:5j11I3H+HvIL+OBdp5nUOQ==,type:str]
kind: ENC[AES256_GCM,data:Ua4T3Wfb,iv:ecJvO04uOh2HtlqYs7/ZWxPnBZXjSq6mejA6clYS9OI=,tag:3+AKchboTVCFCWuyUJTYEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VMmHCrdN810bH2ouRD8=,iv:zpND3m5gAbmqc2XOJphExOE4aO0w8fu4R2qI6BwASLI=,tag:VPhFBB0wUy72toNOQkZJOg==,type:str]
    namespace: ENC[AES256_GCM,data:UKsSmzrxvDrjkq4=,iv:Iu+VRkeMEJwC9znGKaGirLxJuzSDikjabafIUpk/tMc=,tag:LNv83QqCEFKgq+lcQrVDYA==,type:str]
type: ENC[AES256_GCM,data:HYwvltjS,iv:c0Xf/n7WLJwAkoJoPB5ojA+IIKIEMMzWP9LtJd8ChlA=,tag:qMzo5zJmqJK7HBjapeqD+Q==,type:str]
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:9mKXCQwrNpUt0J1qCue+HbNgBKsW/t1Z/Ll1sRKW8GBkhxey2V81oA==,iv:hgPzriLaLwbpmRe7NCiln7STafbohPeUpf5ShpJFbWE=,tag:Q8w3neGaOPc1E4h30CjBTw==,type:str]
sops:
    age:
        - recipient: age12t53xgmu88ye80jtnne6gcfgeytyvvsk6nyetep3xcdw0zthj5msr3dz2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZlBJd0FhdHkrL2psUUla
            Zzkzb2UrL2I5MDB3UVI4REVzWFRTS1FlVlR3Ck9zKzhEbGNwU2xkYzgzM0Qvejlj
            akUvWHJPYkEvNUlJc1VJNE4zVWNhK1UKLS0tIHQ3VTJIbzI1RW9TSEtrOUd1SUM4
            UkphakIvUFVPek9Cb003aWVIVWZ3Y0kKneHfNLOVisoHYXtoUIYvUFTvJkRqNZxQ
            jU708JDz+2w+5EzVIoPpbjQSSdOoiSVIgxncEdwANHW0XPdX1ZYfSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T20:32:09Z"
    mac: ENC[AES256_GCM,data:wskVCOBiw/HFvKrP3rrWKfKAlTX56AZKnhrIOeYxEzzGnQbzRuuQFWGEsvs24R21+GIcfinsba7ZNhwagIhebTfq68nf1s++gGxFx77WAiYMMeeBDEQJlbTge7kyH8GrS9KOviL98X7H1VpmO9HoMIIiYkY14WLmB+IGzb0eMts=,iv:GTt/D7BRoGpNM9Eu9WdEqN1sPo3ZaYCnxgo7R/yVdCU=,tag:X+5jKX7WW8Tjc34kie1/Wg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
