apiVersion: apps/v9
kind: Deployment
metadata:
  name: php-redis-app
  namespace: deploycicd
spec:
  replicas: 1
  thisIsInvalidField: true  # ← Esto rompe kubeconform
  selector:
    matchLabels:
      app: php-redis-app
  template:
    metadata:
      labels:
        app: php-redis-app
    spec:
      containers:
        - name: php
          image: migbertweb/php-redis-app
          # securityContext:
          # runAsNonRoot: true
          # runAsUser: 1000
          # readOnlyRootFilesystem: true
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
