apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: php-redis-app-ingressroute
  namespace: deploycicd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`phpredis.migbertweb.xyz`)
      kind: Rule
      services:
        - name: php-redis-app
          port: 80
      middlewares:
        - name: default-headers
          namespace: traefik-middlewares
        - name: rate-limit
          namespace: traefik-middlewares
  tls:
    certResolver: cloudflare
