repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
  volumeMounts:
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.2.3  # Imagen con ksops instalado
      command: ["/bin/sh", "-c"]
      args:
        - cp /usr/local/bin/ksops /custom-tools/ksops &&
          chmod +x /custom-tools/ksops
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools