apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    path: cluster-issuer-prod.yaml
    options:
      allowNameChange: true