apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portafolio-certificate
  namespace: portafolio
spec:
  secretName: myportafolio-tls  # Nombre del Secret donde se guardará el certificado
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.migbertweb.xyz"