apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - pvc-laravel.yaml
  - cm-laravel.yaml
  - nginx-deployment.yaml
  - laravel-deployment.yaml
  - nginx-service.yaml
  - laravel-service.yaml
  - ingressroute.yaml
generators:
  - secrets/ksops-generator.yaml
images:
  - name: harbor.migbertweb.site/prod-registry/portafolio
    newTag: 1.3.2
