apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: migbert.yanez@gmail.com  # Cambia esto
    server: https://acme-v02.api.letsencrypt.org/directory  # Producción